name: Python CI
on:   
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "--version"

    - name: Ruff Check
      run: ruff check --fix

    - name: Ruff Format
      run: ruff format

    - name: Check for changes
      run: git diff --exit-code

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build
      run: python ./script/build.py
